//
// Created by Wojciech Maciejewski on 07/07/16.
// Copyright (c) 2016 Mobi. All rights reserved.
//

import Foundation

class StringHolder {
    static let user = "Użytkownik"
    static let courses = "Przedmioty"
    static let grades = "Oceny"
    static let schedule = "Plan zajęć"
    static let sendOpinion = "Prześlij opinię"
    static let settings = "Ustawienia"
    static let shareApp = "Podziel się apką"
    static let lecturers = "Wykładowcy"
    static let lecturer = "Wykładowca"
    static let bibliography = "Bibliografia"
    static let classType = "Typ Zajęć"
    static let coordinators = "Koordynatorzy"
    static let cycleLectures = "Zajęcia w cyklu"
    static let description = "Opis"
    static let faculties = "Jednostki"
    static let facultyName = "Nazwa jednostki"
    static let faculty = "Wydział"
    static let leadingLecturers = "Prowadzący"
    static let lecturesConducted = "Prowadzone przedmioty"
    static let students = "Studenci"
    static let passCriteria = "Kryteria Oceny"
    static let courseDetails = "Szczegóły Przedmiotu"
    static let number = "liczba"
    static let programmsNumber = number + " programów:"
    static let cursantNumber = number + " kursantów:"
    static let employyNumber = number + " pracowników:"
    static let callMe = "Zadzwoń"
    static let callMeMessage = "Wybierz numer pod który chcesz zadzwonić"
    static let cancel = "Anuluj"
    static let termin = "termin"
    static let type = "Typ"
    static let group = "Grupa"
    static let bulding = "Budynek"
    static let classRoom = "Sala"
    static let attention  = "Uwaga"
    static let deleteAccount = "Czy na pewno chcesz skasować konto?"
    static let kujonRegulaminUrl = "https://kujon.mobi/regulamin"
    static let noPicture = "Nie ma zdjęcia"
    static let kierunki = "Kierunki"
    static let chooseUsos = "Wybierz Uczelnię"
    static let addedDemo = "Dodano uniwersytet DEMO"
    static let demoId = "DEMO"
    static let moveToUsos = "Zostaniesz przekierowany do USOS żeby się zalogować"
    static let ok = "OK"
    static let statistics = "Informacje"
    static let cycles = "Cykle"
    static let theses = "Prace dyplomowe"
    static let not_auth = "Brak autoryzacji"
    static let terms = "Cykle"
    static let yes = "TAK"
    static let no = "NIE"
    static let identificator = "Identyfikator"
    static let tryb = "Tryb studiów"
    static let time_length = "Czas trwania"
    static let level = "Poziom studiów"
    static let refresh="Odświeżam"
    static let appName = "Kujon"
    static let errorOccures = "Wystąpił błąd podczas komunikacji z serwerem."
    static let no_data = "Brak zajęć w tym dniu"
    static let no_grades = "Brak ocen"
    static let googleType = "GOOGLE"
    static let fbType = "FACEBOOK"
    static let emailType = "EMAIL"
    static let back  = "Powrót"
    static let errorUsos  = "Nie możemy się połączyć z USOS."
    static let usosGreetings = "Gratulacje! Udało Ci się zalogować na "
    static let loggin = "Logowanie"
    static let loggin2 = "Zaloguj się"
    static let contactEmail = "kujon@kujon.mobi"
    static let appItunesLink = "https://itunes.apple.com/pl/app/kujon-klient-usos/id1150898148"
    static let errorPassword = "Bład rejestracji"
    static let emailPasswordError = "Proszę podać poprawny email"
    static let passwordPasswordError = "Hasło musi mieć co najmniej jedną cyfrę i jedną litere"
    static let identicalPasswordError = "Hasła muszą być identyczne"
    static let ectsPoints =  "Suma punktów ECTS"
    static let autorizationError = "Błąd autoryzacji"
    static let search = "Szukaj"
    static let searchResults = "Wyniki wyszukiwania"
    static let searchButtonLabel = "Znajdź"
    static let thesisDetailTitle = "Szczegóły"
    static let authors = "Autorzy"
    static let student = "Student"
    static let supervisors = "Recenzenci"
    static let teacher = "Wykładowca"
    static let none = "Brak"
    static let none_lowercase = "brak"
    static let messages = "Wiadomości"
    static let noMessages = "Uff, nie masz żadnych wiadomości"
    static let refreshControlUniversalMessage = "Przesuń, żeby odświeżyć"
    static let errorRetrievingMessages = "Wystąpił problem podczas pobierania wiadomości"
    static let errorAlertTitle = "Błąd"
    static let details = "Szczegóły"
    static let usosesGeneralInfo = "Jeżeli Twojej uczelni nie ma na liście, oznacza to, że nie korzysta ona ze wspieranego przez Kujona systemu USOS."
    static let demoMode = "Tryb demo"
    static let productionMode = "Tryb produkcyjny"
    static let loginError = "Błąd logowania"
    static let unknownErrorMessage = "Wystąpił nieznany błąd"
    static let shouldOpenAppSettingsForNotifications = "Opcję powiadomień Kujona możesz zmienić w ustawieniach systemowych iOS. Czy chcesz otworzyć ustawienia systemowe?"
    static let kierunekTitle = "Kierunek"


}
