//
// Created by Wojciech Maciejewski on 07/07/16.
// Copyright (c) 2016 Mobi. All rights reserved.
//

import Foundation

class StringHolder {
    static let user = "Użytkownik"
    static let courses = "Przedmioty"
    static let grades = "Oceny"
    static let schedule = "Plan Zajęć"
    static let sendOpinion = "Prześlij opinię"
    static let settings = "Ustawienia"
    static let shareApp = "Podziel się"
    static let lecturers = "Wykładowcy"
    static let lecturer = "Wykładowca"
    static let bibliography = "Bibliografia"
    static let classType = "Typ Zajęć"
    static let coordinators = "Koordynatorzy"
    static let cycleLectures = "Zajęcia w cyklu"
    static let description = "Opis"
    static let faculties = "Jednostki"
    static let faculty = "Jednostka"
    static let leadingLecturers = "Prowadzący"
    static let students = "Studenci"
    static let passCriteria = "Kryteria Oceny"
    static let courseDetails = "Szczegóły Przedmiotu"
    static let number = "liczba"
    static let programmsNumber = number + " programów:"
    static let cursantNumber = number + " kursantów:"
    static let employyNumber = number + " pracowników:"
    static let callMe = "Zadzwoń"
    static let callMeMessage = "Wybierz numer pod który chcesz zadzwonić"
    static let cancel = "Anuluj"
    static let termin = "termin"
    static let type = "Typ"
    static let group = "Grupa"
    static let bulding = "Budynek"
    static let classRoom = "Sala"
    static let attention  = "Uwaga"
    static let deleteAccount = "Czy na pewno chcesz skasować konto?"
    static let kujonRegulaminUrl = "https://kujon.mobi/regulamin"
    static let noPicture = "Nie ma zdjęcia"
    static let kierunki = "Kierunki"
    static let chooseUsos = "Wybierz Uczelnię"
    static let addedDemo = "Dodano uniwersytet DEMO"
    static let demoId = "DEMO"
    static let moveToUsos = "Zostaniesz przekierowany do USOS żeby się zalogować"
    static let ok = "OK"
    static let statistics = "Statystyki"
    static let cycles = "Cykle"
    static let not_auth = "Brak autoryzacji"
    static let terms = "Cykle"
    static let yes = "TAK"
    static let no = "NIE"
}
